version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Iniciando Build
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:    
    - ./target/filmes.api-0.0.1-SNAPSHOT.jar
    - ./scripts/*.sh
    - appspec.yml
