version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Iniciando Build
      - cd ./src/backend/filmes.api/
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./src/backend/filmes.api/appspec.yml
    - ./src/backend/filmes.api/scripts/*
    - ./src/backend/filmes.api/target/filmes.api-0.0.1-SNAPSHOT.jar